
import './globals.css'



export const metadata = {
  manifest: "/manifest.json",
  title: 'Recept Genrater',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
